CREATE TABLE `kovaaks_scores` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`scenario_name` text NOT NULL,
	`mode` text NOT NULL,
	`run_datetime_text` text NOT NULL,
	`run_epoch_sec` integer NOT NULL,
	`source_filename` text NOT NULL,
	`accuracy` real NOT NULL,
	`bot` text NOT NULL,
	`cheated` integer NOT NULL,
	`damage_done` real NOT NULL,
	`damage_possible` real NOT NULL,
	`efficiency` real NOT NULL,
	`hits` integer NOT NULL,
	`kill_number` integer NOT NULL,
	`overshots` integer NOT NULL,
	`shots` integer NOT NULL,
	`ttk` text NOT NULL,
	`timestamp` text NOT NULL,
	`weapon` text NOT NULL
);
