/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsIndexRouteImport } from './routes/reports/index'
import { Route as KnowledgesIndexRouteImport } from './routes/knowledges/index'
import { Route as DeviceIndexRouteImport } from './routes/device/index'
import { Route as AuthAuthViewRouteImport } from './routes/auth/$authView'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AccountSettingsRouteImport } from './routes/account/settings'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgesIndexRoute = KnowledgesIndexRouteImport.update({
  id: '/knowledges/',
  path: '/knowledges/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceIndexRoute = DeviceIndexRouteImport.update({
  id: '/device/',
  path: '/device/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthViewRoute = AuthAuthViewRouteImport.update({
  id: '/auth/$authView',
  path: '/auth/$authView',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/account/settings',
  path: '/account/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/stats': typeof StatsRoute
  '/account/settings': typeof AccountSettingsRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/device': typeof DeviceIndexRoute
  '/knowledges': typeof KnowledgesIndexRoute
  '/reports': typeof ReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/stats': typeof StatsRoute
  '/account/settings': typeof AccountSettingsRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/device': typeof DeviceIndexRoute
  '/knowledges': typeof KnowledgesIndexRoute
  '/reports': typeof ReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/stats': typeof StatsRoute
  '/account/settings': typeof AccountSettingsRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/device/': typeof DeviceIndexRoute
  '/knowledges/': typeof KnowledgesIndexRoute
  '/reports/': typeof ReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/stats'
    | '/account/settings'
    | '/api/$'
    | '/auth/$authView'
    | '/device'
    | '/knowledges'
    | '/reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/stats'
    | '/account/settings'
    | '/api/$'
    | '/auth/$authView'
    | '/device'
    | '/knowledges'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/stats'
    | '/account/settings'
    | '/api/$'
    | '/auth/$authView'
    | '/device/'
    | '/knowledges/'
    | '/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StatsRoute: typeof StatsRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  ApiSplatRoute: typeof ApiSplatRoute
  AuthAuthViewRoute: typeof AuthAuthViewRoute
  DeviceIndexRoute: typeof DeviceIndexRoute
  KnowledgesIndexRoute: typeof KnowledgesIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledges/': {
      id: '/knowledges/'
      path: '/knowledges'
      fullPath: '/knowledges'
      preLoaderRoute: typeof KnowledgesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device/': {
      id: '/device/'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$authView': {
      id: '/auth/$authView'
      path: '/auth/$authView'
      fullPath: '/auth/$authView'
      preLoaderRoute: typeof AuthAuthViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StatsRoute: StatsRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  ApiSplatRoute: ApiSplatRoute,
  AuthAuthViewRoute: AuthAuthViewRoute,
  DeviceIndexRoute: DeviceIndexRoute,
  KnowledgesIndexRoute: KnowledgesIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
